# ~/.config/starship.toml

# Add a newline before prompt for clarity
add_newline = true

# Use bold white for the directory path
[directory]
style = "bold white"
read_only = " "

# Git branch info in bright white
[git_branch]
symbol = " "
style = "bold white"

# Git status in grayscale
[git_status]
style = "white"
conflicted = "⚠️ "
ahead = "⇡${count}"
behind = "⇣${count}"
staged = "●${count}"
deleted = "✖${count}"
renamed = "➜${count}"
modified = "✎${count}"
untracked = "…${count}"

# NodeJS version in dim white
[nodejs]
style = "dim white"

# Rust version
[rust]
style = "dim white"

# Python version
[python]
style = "dim white"

# Time module in white
[time]
disabled = false
format = "[$time]($style) "
style = "white"

# Battery info in white with unicode symbol
[battery]
full_symbol = " "
charging_symbol = " "
discharging_symbol = " "
style = "white"

# Username and hostname in white for SSH sessions
[username]
style = "bold white"

[hostname]
style = "bold white"

# Status code (last command success/failure)
[status]
style_success = "white"
style_failure = "bold white"
symbol = "❯ "

# Customize prompt symbol to be a simple white arrow
[character]
success_symbol = "❯ "
error_symbol = "❯ "
style_success = "white"
style_failure = "bold white"
use_symbol_for_status = true
