# Palette for Catppuccin Mocha ðŸŒ¿ theme
[palettes.catppuccin_mocha]
background = "#1E1E2E"
current_line = "#2A2A37"
foreground = "#CDD6F4"
comment = "#8C8F96"
cyan = "#94E2D5"
green = "#A6E3A1"
orange = "#F9E2AF"
pink = "#F5C2E7"
purple = "#CBA6F7"
red = "#F38BA8"
yellow = "#F9E2AF"

# Prompt segments

[aws]
style = "bold orange"

[character]
error_symbol = "[Î»](bold red)"
success_symbol = "[Î»](bold green)"

[cmd_duration]
style = "bold yellow"

[directory]
style = "bold green"

[git_branch]
style = "bold pink"

[git_status]
style = "bold red"

[hostname]
style = "bold purple"

[username]
format = "[$user]($style) on "
style_user = "bold cyan"

# Git branch formatting
[git_branch]
style = "bold pink"
format = "on [$branch]($style)"

# Define colors for the prompt segments
[cmd_duration]
style = "bold yellow"
